### ISSUE TITLE
Clarifications on instructions for using in conjunction with GoReleaser?

### ISSUE THREAD

**Issue by wakatara** [canonical/action-build#2]
I've been trying all afternoon to get a snap to release via [GoReleaser](https://github.com/goreleaser/goreleaser) and Github Actions (failed once already with another action.). My former action kept failing (even though it kept saying snapcraft was installed) and dying. This would be the first snap I've created and tried publishing to the snapcraft store.

So, I am simply trying to understand if there are additional steps required besides using this action and installing it and then having goreleaser hand off for everything else (I have homebrew packages handled fine right now). 

What I am hoping to do is the following: 

``` yaml
name: goreleaser

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*.*.*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Snap Action Build
        uses: snapcore/action-build@v1
      -
        name: Unshallow
        run: git fetch --prune --unshallow
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.3
      -
        name: Snapcraft Login
        if: success() && startsWith(github.ref, 'refs/tags/v')
        env:
          SNAPCRAFT_LOGIN: ${{ secrets.SNAPCRAFT_LOGIN }}
        run: |
          snapcraft login --with <(echo "$SNAPCRAFT_LOGIN")
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_HARSH_HOMEBREW_PUBLISHER }}
```

My release yaml file looks somewhat like this (stolen from the goreleaser build.yml itself)

``` yaml
everything: here works fine for building and packing the binaries on GH
and: pushing a homebrew formula to a separate repo to tap
...
snapcrafts:
  - name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    summary: Yadda yadda yadda 
    description: |
      Better, longer yadda .
      Mutliline yadda even.
    grade: stable
    confinement: strict
    publish: true
```

I've created a proper secrets key for the snapcraft login but at this point just want to confirm that I am on the right track or I am being dense. Goreleaser does not take care of the snapcraft and dependencies installation so assuming this does. 

thanks!
