### ISSUE TITLE
[Bug] Environment variable in action-build

### ISSUE THREAD

**Issue by talregev** [canonical/action-build#41]
Environment variable in action-build.
I want to be able to pass environment variable that I define in workflow. like secrets or other environment variable that define in:
```yaml
env:
 ENV1: value1

jobs:
  create-snap:
    name: Create snap
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Build snap
        uses: snapcore/action-build@v1
        env:
           ENV2: value2


```

I want to be able to access both envs.

Currently I cannot do it. It not take these envs.
Can you make it happen?
