### ISSUE TITLE
Handling Snaps that build for multiple architectures

### ISSUE THREAD

**Issue by kian99** [canonical/action-build#54]
Hi,

Looking at the source I see that this action will only grab the name of a single snap in the output directory. We have a use case in which our snapcraft.yaml file is cross-compiling our application and we use the `architectures` directive to build multiple snaps for various architectures.

It would be great if the action could support this workflow.

**Comment by jhenstridge** [comment]
Is this a case of running the action multiple times against the same working copy in a single job in the workflow? I didn't think snapcraft could build multiple versions of the snap in a single invocation.

Would setting the output to the most recently modified `.snap` file do what you want?

**Comment by kian99** [comment]
Hi, not quite. We only run the action once and a single invocation of snapcraft builds multiple snaps for different architectures (specifically cross-compiling so it all builds on the same machine). This is done using the [architectures](https://snapcraft.io/docs/architectures) syntax. 

For reference, the way I'm currently handling this is with the following snippet,
```
snaps=($(ls ./*.snap))
for snapPath in ${snaps[@]}; do
  snapcraft upload --release ${{ env.CLIENT_SNAP_NAME }}/edge "${snapPath}"
done
```

Ultimately the work around above is easy enough but I thought I'd make the issue known.

**Comment by Mailaender** [comment]
There is https://github.com/diddlesnaps/snapcraft-multiarch-action but it would be nice to have official support.

**Comment by kian99** [comment]
I've currently adopted the below approach which works nicely. So I'll close the issue and hope this snippet helps others.
```
jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        strategy:
          matrix:
            arch: [amd64, arm64, s390x]
        steps:
          - uses: actions/checkout@v4
          - name: Setup snap to build
            run: ln -s ./snaps/client/core22/snapcraft.yaml
          - uses: snapcore/action-build@v1
            id: build
            with:
              snapcraft-args: "--build-for=${{ matrix.arch }}"
          - if: inputs.release == true
            uses: snapcore/action-publish@v1
            env:
                SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
            with:
                snap: ${{ steps.build.outputs.snap }}
                release: latest/edge
```
