### ISSUE TITLE
Flaky builds

### ISSUE THREAD

**Issue by edlerd** [canonical/action-build#75]
We frequently see builds failing due to unstable infrastructure. Suspecting network problems as the root cause. See [this run in AMS](https://github.com/canonical/ams/actions/runs/9413389351/job/25930041808?pr=105) and the relevant screenshot below

![image](https://github.com/snapcore/action-build/assets/1155472/3f4bc2af-d0bd-43ab-aabe-6474b29030c2)

Can we ensure the builds have a stable network connection and reduce the flakyness of builds?

Or retry the build automatically on network problems? Currently, we have to retry the builds manually on those type of errors.

**Comment by jhenstridge** [comment]
It's a bit hard to tell what is going wrong just from that screenshot, and any fix will probably need to be on the Snapcraft side rather than this action.

One thing that might be helpful in diagnosing the problem would be to save the Snapcraft log file on error. This could be done by adding the following to your workflow:

```yaml
  - if: failure()
    uses: action/upload-artifact@v4
    with:
      name: snapcraft-logs
      path: ~/.local/state/snapcraft/log/*.log
```

This step would only run if some previous step in the job had failed. Alternatively you could remove the `if: failure()` to always collect the log.
