### ISSUE TITLE
action-build is no longer interpreting environment variables

### ISSUE THREAD

**Issue by Guillaumebeuzeboc** [canonical/action-build#79]
The new release of action-build `1.3.0` appears to no longer import or use the environment variables of the GH step or job.

In my case:
```
    env:
      SNAPCRAFT_BUILDER_ID: ${{ github.run_id }}
    steps:
      [...]
      - uses: snapcore/action-build@v1
        env:
          SNAPCRAFT_REMOTE_BUILD_STRATEGY: force-fallback
        with:
          path: .
          snapcraft-args: "remote-build --launchpad-accept-public-upload --build-id ${{ matrix.snap_names }}-${{ SNAPCRAFT_BUILDER_ID }}"
```
to be interpreted as
```
/usr/bin/sudo -u runner -E snapcraft remote-build --launchpad-accept-public-upload --build-id noetic-desktop-amd64-${SNAPCRAFT_BUILDER_ID}
```
(SNAPCRAFT_BUILDER_ID is not interpreted)

Could be that [this recent change induced the new behaviour](https://github.com/snapcore/action-build/commit/5c9748de47580bff7aa48721d7463e1b544c5f21)

Our CI that [was working fine before stopped working](https://github.com/ubuntu-robotics/ros-content-sharing-snaps/actions/runs/9935620747/job/27454616218#step:6:27) after this release.

Is it an intended behaviour?
