### ISSUE TITLE
Actions fail with `Unable to resolve action` failure

### ISSUE THREAD

**Issue by KirioXX** [canonical/action-build#82]
Hi,

We have seen since last Friday that our github actions started to fail with the following error:
```sh
Error: Unable to resolve action `snapcore/action-build@v1`, unable to find version `v1`
```

Is there something that we can do to resolve this issue?

Here is also our github action config:
```yaml
name: Build and release arm64 snap

on:
  release:
    types:
      - released

env:
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

jobs:
  build:
    runs-on: raspberry-pi-arm64
    outputs:
      snap-file: ${{ steps.build.outputs.snap }}
    steps:
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - uses: actions/checkout@v4

      - name: 🚢 Build arm64 snap
        uses: snapcore/action-build@v1
        id: build
        with:
          snapcraft-args: |
            --build-for=arm64
            --bind-ssh

      - uses: actions/upload-artifact@v4
        with:
          name: build_output
          path: ${{ steps.build.outputs.snap }}

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        id: download
        with:
          name: build_output
          path: build_output/

      - name: Get File
        id: get_file
        run: |
          echo "download-path=$(find build_output/ -name '*.snap' -type f)" >> $GITHUB_STATE

      - uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
        with:
          snap: ${{ steps.get_file.outputs.download-path }}
          release: edge

  sent_sentry:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - uses: actions/checkout@v4

      # Setup Flutter
      - uses: kuhnroyal/flutter-fvm-config-action@v2
        id: fvm-config-action
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}
          cache: true

      - name: "Add env file to all projects"
        run: mkdir -p assets && touch assets/.env
      - name: "Install dependencies"
        run: flutter pub get
      - name: Upload source to Sentry
        run: |
          set -e # fail if any command fails
          VERSION=`grep 'version:' pubspec.yaml | awk '{print $2}'`
          SENTRY_RELEASE=${VERSION}
          echo "Uploading source to Sentry using SENTRY_RELEASE=$SENTRY_RELEASE"
          flutter packages pub run sentry_dart_plugin
```
